language: node_js
node_js:
- 4.2.1
sudo: false
before_script:
- npm install -g gulp
# before_deploy: gulp build
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAILMXWFWLI2GAUL3A
  secret_access_key:
    secure: pbgLL2Aha4q/V1But7DSY3NkY71VR2ZgQVJv3fFuG8m47ZH6gOkAzL6F1ka76UZat9XRl0OHCNarBMYbFwjnk0GrEKX/wMHa04oVIU3CuXoz63uE6RUMiiRTW8cxltBFZ/ojuq5jna+Wcd9e1EUJTa/ZnSnFqIV7PUl/Sr86PPPn7mPBQZqoELrpPAGYX4sTfBtx127k/D/lF2Qnp6ebbNeK3U2xT82h8p6lK07lovkS4d5l7mwO6QdPtmiELAt+OqvkNIG6YlmgX9rq07urxVshbl7AKUocIBzlAtXW+12dkoZlD3OSgAiO0bWVSXjo/6DscgirCPLCScuGpJgzdbNx3gUPLtUpjBziWqVA8KQkSzV5suVhI8WlvFE23Z5g9Wx0LnCHoETqCJ0CwXZblMQ9AaPDmu6tLN4f2kCJ8tj/RgOYGQrIA5jMjvw5Vnu91S7qzlNje33YOS0EYWMyN66ayY4JUynj3curAqi75AjaNsYCa9hxXmSzxcTj2JcjAQDJWx3qXa0aOKHdOUWGudLky5wAbyHB5WonBP2p3kN/StX7ikNVmSYZvNK3mqAsAD45/y/0KiRvCcqQ2FKDFe11iIgsiGR8z6qRgF1q7UwdZ3c8ukRs/EC8Dx3cI8WC3Yyy0DXEOkU0FukmkZB1IKpQt1W9+6u7PWNSC+lyDKo=
  bucket: cdn.ecor.biz
  acl: public_read
  local_dir: /home/travis/build/ecorventures/webassets/dist
  on:
    repo: ecorventures/webassets
notifications:
  hipchat:
    rooms:
      secure: RP1Nk54+pVdkm9S4oa1W19t/18TqCnYffBKrrGEvFmW0ZG6CW1tgejyozunKAccOi/tfFiSd4SyQ3nCdMyk9U6EBedRe2FeDQpYw2mlCcJmsu1J84bI8QLLE7AY16dPjM0/DY8R3aPa3Ey7ZwsbemEIVstiaD3hn28cwA2vYOqd1TGIEa0Y2Or78pOu7fcaiatN0ANVrVUEmtm7M0gaGvw6DusTcL9+vXQfCOk7mASMwpuN/JqlAq+9yWJnNcs96AuJzqldbH7O8u5A+2oGik8RhGsTPLSPf6rIOxqTh9hzXR1soM+/1vykDZZAT3BQkXJ6EuzfS4uCw3y54d6Fhft3mBJsis7/DnsOf73WLxK05RlyRJWd5SHF0D4AOpkxEfWDLF4yCUfybxAv3tpaiT9BRxRx8Sg/DwqB9pGuepYzUsZySjmTDUUw13m/0xpD3nskAPF9KtnREgJmqdmAwJESrmO4IBu8dL2i6oEqxq1gWNQ8NX25G43pfbz3Q4cfXXuGnT0ri/Stg3UmgRBC8xxpzbpINWx8h3atfnnj+1/WDBSFk88xXaYcLSX0GDEt/7YQpK+iBC87N5vZVlo76+061+dku/XaxhDbvgwlO3EcZMUEAhQCBdnMCX66D6RYI47Y44u4q5wnlTKQXaSQhv+GO5aOCNYsOSr4bn5w8cNY=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    on_pull_requests: false
